---
gateway:
  port: 7070
  index: "/"
  ssl:
    use: false
    cert-path: null
    key-path: null
  login:
    page: "/web/login"
    api: null
  jwt:
    use: false
    check-expiration: false
    expires-min: null
  session:
    use: false
    timeout-hour: null
  redirects:
  - from: "/"
    to: "/web/"
  white-referer:
  - "login"
  frontends:
  - path: "/web"
    dir: "/Users/aruis/develop/workspace-github/MuYunGateway/src/test/resources/webroot"
    not-found-reroute: true
    secured: true
    regex: false
    comment: null
    no-cache:
    - "/"
    - "/index.html"
    allowlist:
    - ".*\\..*"
    - "/login"
  upstreams:
  - path: "/api"
    secured: true
    regex: false
    comment: null
    no-cache: []
    allowlist: []
    backends:
    - url: "http://127.0.0.1:8090/api/"
      weight: 1
    - url: "http://127.0.0.1:8091/api/"
      weight: 1
