---
gateway:
  port: 7070
  index: "/web/"
  ssl:
    use: false
    cert-path: null
    key-path: null
  login:
    path: "/api/sso/login"
    page: "/web/login"
    api: "http://127.0.0.1:8080/api/sso/login"
  jwt:
    use: false
    check-expiration: false
    expires-min: null
  session:
    use: false
    timeout-hour: null
  redirects:
  white-referer:
  - "login"
  frontends:
  - path: "/web"
    dir: "/Users/aruis/develop/workspace-bsy/unicom_xinan_project/dist"
    not-found-reroute: true
    secured: true
    regex: false
    comment: null
    no-cache:
    - "/"
    - "/index.html"
    allowlist:
    - ".*\\..*"
    - "/login"
  upstreams:
  - path: "/api"
    secured: true
    regex: false
    comment: null
    no-cache: []
    allowlist: []
    backends:
    - url: "http://127.0.0.1:8080/api/"
      weight: 1
