gateway:
  index: /
  ssl:
    use: false
    cert_path:
    key_path:
  login:
    page: /web/login
    api:
  jwt:
    use: false
    check-expiration: false
    expires-min:
  session:
    use: false
    timeout-hour:
  redirects:
    - from: /
      to: /web/
  white-referer:
    - login
  frontends:
    - path: web
      dir: /Users/aruis/develop/workspace-github/MuYunGateway/src/test/resources/webroot
      notFoundReroute: /
      protect: true
      regex: false
      comment:
      noStore:
        - "/"
        - "/index.html"
      whiteList:
        - ".*\\..*"
        - "/login"
quarkus:
  http:
    port: 8888
    enable-compression: true
    limits:
      max-header-size: 64K
  rest:
    path: /api
  banner:
    path: banner.txt
  log:
    level: INFO
    console:
      enable: true
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] (%t) %s%e%n"
    file:
      enable: false
      path: logs/muyun-gateway.log
      level: DEBUG
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] (%t) %s%e%n"
      rotation:
        file-suffix: .yyyy-MM-dd
        rotate-on-boot: true
        max-backup-index: 7
